services:
  mysql-db:
    networks:
      - auction-network
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234

# init SQL로 대체
#      MYSQL_DATABASE: userAuth
#      MYSQL_USER: auth_user
#      MYSQL_PASSWORD: auth_password
    ports:
      - "3306:3306"
    volumes: # 컨테이너 내부에 생성될 볼륨
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # 초기화 스크립트 추가

  redis-db:
    networks:
      - auction-network
    image: redis:7.0
    container_name: redis-db
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mongo-db:
    networks:
      - auction-network
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes: # 호스트 시스템에 생성된 볼륨
  mysql-data:
  redis-data:
  mongo-data:

networks:
  auction-network: