services:
  mysql-db:
    networks:
      - auction-network
    image: mysql:8.0

    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234

# init SQL로 대체
#      MYSQL_DATABASE: userAuth
#      MYSQL_USER: auth_user
#      MYSQL_PASSWORD: auth_password
    ports:
      - "3306:3306"
    volumes: # MySQL 데이터가 컨테이너 재시작이나 삭제 후에도 유지
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # 초기화 스크립트 추가

volumes: # MySQL 데이터를 저장할 물리적 공간을 할당하여 데이터를 영구적으로 보존
  mysql-data:

networks:
  auction-network: