server:
  port: 8082

spring:
  application:
    name: auction-service

  profiles:
    active: prod

  cloud:
    openfeign:
      circuit breaker:
        enabled: true
        alphanumeric-ids:
          enabled: true

  resilience4j:
    circuit breaker:
      configs:
        default:
          registerHealthIndicator: true
          slidingWindowType: COUNT_BASED
          slidingWindowSize: 5
          minimumNumberOfCalls: 5
          slowCallRateThreshold: 100
          slowCallDurationThreshold: 60000
          failureRateThreshold: 50
          permittedNumberOfCallsInHalfOpenState: 3
          waitDurationInOpenState: 20s

message:
  exchange: app
  queue:
    bid-register: app.bid.register
    auction-info: app.auction.info