server:
  port: 8082

spring:
  application:
    name: auction-service
  mvc:
    static-path-pattern: /swagger-ui/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 드라이버 클래스 이름
    url: jdbc:mysql://mysql-db:3306/auction  # MySQL 데이터베이스 URL
    username: auction_user  # 데이터베이스 사용자 이름
    password: auction_password  # 데이터베이스 비밀번호

  data:
    redis:
      host: redis-db
      port: 6379
      username: default
      password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true
        format-sql: true
        generate-ddl: true

message:
  exchange: app
  queue:
    bid-register: app.bid.register

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
