eureka:
  client:
    register-with-eureka: false # 자기 자신을 서버로 등록x
    fetch-registry: false # 다른 서비스 레지스트리 안가져옴
    service-url:
      defaultZone: http://eureka-service:8761/eureka/ # 컨테이너 이름을 사용
  instance:
    hostname: eureka-server # Eureka에 자신을 등록할 때 사용할 호스트 이름