spring:
  mvc:
    static-path-pattern: /swagger-ui/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 드라이버 클래스 이름
    url: jdbc:mysql://mysql-db:3306/coinpay  # MySQL 데이터베이스 URL
    username: coinpay_user  # 데이터베이스 사용자 이름
    password: coinpay_password  # 데이터베이스 비밀번호

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true
        format-sql: true
        generate-ddl: true

    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: >
        classpath:data/coinpay.sql

  rabbitmq:
    host: rabbitMQ-server
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/