server:
  port: 8081

spring:
  application:
    name: userAuth-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 드라이버 클래스 이름
    url: jdbc:mysql://mysql-db:3306/userAuth  # MySQL 데이터베이스 URL
    username: auth_user  # 데이터베이스 사용자 이름
    password: auth_password  # 데이터베이스 비밀번호

  data:
    redis:
      host: redis-db # 성진 WSL 주소 -> localhost로 변경하기
      port: 6379
      username: default
      password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true
        format-sql: true
        generate-ddl: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

jwt:
  secret:
    key: YW55IHNlY3JldCBleGFtcGxlIHNlY3JldCBrZXkgZm9yIGp3dA==
  expiration: 3600000

