server:
  port: 8081

spring:
  application:
    name: userAuth-service

  profiles:
    active: dev

jwt:
  secret:
    key: YW55IHNlY3JldCBleGFtcGxlIHNlY3JldCBrZXkgZm9yIGp3dA==
  expiration: 3600000