server:
  port: 8083

spring:
  application:
    name: bidwin-service
  mvc:
    static-path-pattern: /swagger-ui/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 드라이버 클래스 이름
    url: jdbc:mysql://mysql-db:3306/bidwin  # MySQL 데이터베이스 URL
    username: bidwin_user  # 데이터베이스 사용자 이름
    password: bidwin_password  # 데이터베이스 비밀번호
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true
        format-sql: true
        generate-ddl: true

  rabbitmq:
    host: rabbitMQ-server
    port: 5672
    username: guest
    password: guest

  cloud:
    openfeign:
      circuit breaker:
        enabled: true
        alphanumeric-ids:
          enabled: true

  resilience4j:
    circuit breaker:
      configs:
        default:
          registerHealthIndicator: true
          slidingWindowType: COUNT_BASED
          slidingWindowSize: 5
          minimumNumberOfCalls: 5
          slowCallRateThreshold: 100
          slowCallDurationThreshold: 60000
          failureRateThreshold: 50
          permittedNumberOfCallsInHalfOpenState: 3
          waitDurationInOpenState: 20s

message:
  exchange: app
  queue:
    bid-cancel: app.bid.cancel
    bid-register: app.bid.register

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
